name: Release

on:
  push:
    tags:
      - 'v*.*.*'
jobs:  
  release-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1      
      -
        name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_REFrefs/tags/}
          echo ::set-output name=version::${VERSION}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            saucelabs/stt-cypress-mocha-node:latest
            saucelabs/stt-cypress-mocha-node:${{ steps.prep.outputs.version }}
  bundle-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - name: List bundle contents
        run: ls -R bundle/
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REFrefs/*/}
      - name: Archive bundle
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Compress-Archive bundle/ cypress-win-${{ steps.vars.outputs.tag }}.zip
          azPSVersion: '3.1.0'
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: cypress-win-${{ steps.vars.outputs.tag }}.zip
          path: |
            ./cypress-win-${{ steps.vars.outputs.tag }}.zip
