name: Integration Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - packages/sauce-cypress-runner

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci --production
      - name: Run integration tests
        env:
          SAUCE_CYPRESS_VIDEO_RECORDING: false
        run: bash tests/integration/integration-tests.sh

