name: Test Cypress

on:
  pull_request:
    branches:
      - master
    paths:
      - packages/sauce-cypress-runner/**/*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sauce-cypress-runner
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/build-push-action@v1
        with:
          path: packages/sauce-cypress-runner
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saucelabs/stt-cypress-mocha-node
          tag_with_ref: true
          cache_froms: saucelabs/stt-cypress-mocha-node:latest
          push: false

  build-ubuntu-bundle-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sauce-cypress-runner
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/

  build-windows-bundle-and-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: packages/sauce-cypress-runner
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/
      -
        name: Print npm version
        run: bundle/node_modules/.bin/npm -v
